/* Copyright (c) 2017 Mozilla
   Auto-generated from training — this is a stub for compilation.
   Replace with actual trained weights from the RNNoise repository. */
/**
   @file rnn_data.h
   @brief Pre-trained RNN model weights (stub)
   
   NOTE: These are zero-initialized stub weights that produce pass-through
   behavior. To get actual noise suppression, replace this file with the
   rnn_data.h generated by the RNNoise training scripts, or download the
   pre-trained weights from https://github.com/xiph/rnnoise
*/
#ifndef RNN_DATA_H
#define RNN_DATA_H

#include "rnn.h"
#include "freq.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Model dimensions (from the default RNNoise model) */
#define INPUT_DENSE_SIZE 24
#define VAD_GRU_SIZE 24
#define NOISE_GRU_SIZE 48
#define DENOISE_GRU_SIZE 96
#define DENOISE_OUTPUT_SIZE 22
#define VAD_OUTPUT_SIZE 1

/* Stub weight arrays — zero-initialized for compilation.
   With zero weights, the model outputs unity gains (pass-through).
   Replace with actual trained weights for real noise suppression. */

static const float input_dense_weights[NB_FEATURES * INPUT_DENSE_SIZE] = {0};
static const float input_dense_bias[INPUT_DENSE_SIZE] = {0};

static const float vad_gru_weights[INPUT_DENSE_SIZE * VAD_GRU_SIZE * 3] = {0};
static const float vad_gru_recurrent_weights[VAD_GRU_SIZE * VAD_GRU_SIZE * 3] = {0};
static const float vad_gru_bias[VAD_GRU_SIZE * 3] = {0};

static const float noise_gru_weights[(INPUT_DENSE_SIZE + VAD_GRU_SIZE) * NOISE_GRU_SIZE * 3] = {0};
static const float noise_gru_recurrent_weights[NOISE_GRU_SIZE * NOISE_GRU_SIZE * 3] = {0};
static const float noise_gru_bias[NOISE_GRU_SIZE * 3] = {0};

static const float denoise_gru_weights[(INPUT_DENSE_SIZE + NOISE_GRU_SIZE) * DENOISE_GRU_SIZE * 3] = {0};
static const float denoise_gru_recurrent_weights[DENOISE_GRU_SIZE * DENOISE_GRU_SIZE * 3] = {0};
static const float denoise_gru_bias[DENOISE_GRU_SIZE * 3] = {0};

static const float denoise_output_weights[DENOISE_GRU_SIZE * DENOISE_OUTPUT_SIZE] = {0};
static const float denoise_output_bias[DENOISE_OUTPUT_SIZE] = {0};

static const float vad_output_weights[VAD_GRU_SIZE * VAD_OUTPUT_SIZE] = {0};
static const float vad_output_bias[VAD_OUTPUT_SIZE] = {0};

/* Get the stub model — called from denoise.c when no model is provided */
static inline const RNNModel* rnnoise_get_stub_model(void) {
    static const RNNModel model = {
        0, /* model_loaded = 0 means stub/pass-through */
        /* input_dense */
        { input_dense_bias, input_dense_weights, NB_FEATURES, INPUT_DENSE_SIZE, ACTIVATION_TANH },
        /* vad_gru */
        { vad_gru_bias, vad_gru_weights, vad_gru_recurrent_weights, INPUT_DENSE_SIZE, VAD_GRU_SIZE, ACTIVATION_RELU },
        /* noise_gru */
        { noise_gru_bias, noise_gru_weights, noise_gru_recurrent_weights, INPUT_DENSE_SIZE + VAD_GRU_SIZE, NOISE_GRU_SIZE, ACTIVATION_RELU },
        /* denoise_gru */
        { denoise_gru_bias, denoise_gru_weights, denoise_gru_recurrent_weights, INPUT_DENSE_SIZE + NOISE_GRU_SIZE, DENOISE_GRU_SIZE, ACTIVATION_RELU },
        /* denoise_output */
        { denoise_output_bias, denoise_output_weights, DENOISE_GRU_SIZE, DENOISE_OUTPUT_SIZE, ACTIVATION_SIGMOID },
        /* vad_output */
        { vad_output_bias, vad_output_weights, VAD_GRU_SIZE, VAD_OUTPUT_SIZE, ACTIVATION_SIGMOID }
    };
    return &model;
}

#ifdef __cplusplus
}
#endif

#endif /* RNN_DATA_H */
